begin;
select plan(16);
select ok(has_table_privilege('anon', 'public.designs', 'SELECT'), 'anonymous catalog reads granted');
select ok(not has_table_privilege('anon', 'public.profiles', 'SELECT'), 'anonymous profiles denied');
select ok(has_table_privilege('authenticated', 'public.profiles', 'SELECT'), 'signed-in profile reads granted');
select ok(has_column_privilege('authenticated', 'public.profiles', 'display_name', 'UPDATE'), 'profile name editable');
select ok(not has_column_privilege('authenticated', 'public.profiles', 'role', 'UPDATE'), 'role escalation denied');
select ok(not has_column_privilege('authenticated', 'public.boutiques', 'status', 'UPDATE'), 'self-verification denied');
select ok(not has_table_privilege('authenticated', 'public.boutiques', 'INSERT'), 'onboarding must use validated RPC');
select ok(not has_column_privilege('authenticated', 'public.boutique_profiles', 'rating', 'UPDATE'), 'self-rating denied');
select ok(has_column_privilege('authenticated', 'public.designs', 'title', 'INSERT'), 'portfolio creation granted');
select ok(not has_column_privilege('authenticated', 'public.designs', 'is_featured', 'INSERT'), 'self-featuring on insert denied');
select ok(not has_column_privilege('authenticated', 'public.designs', 'is_featured', 'UPDATE'), 'self-featuring on update denied');
select ok(has_table_privilege('service_role', 'public.order_payment_attempts', 'SELECT'), 'server payment reads granted');
select ok(has_sequence_privilege('service_role', 'public.audit_events_id_seq', 'USAGE'), 'server audit sequence granted');
select ok(not has_function_privilege('anon', 'public.share_outfit_request(uuid,uuid,boolean,boolean,boolean)', 'EXECUTE'), 'anonymous sharing RPC denied');
select ok(has_function_privilege('authenticated', 'public.share_outfit_request(uuid,uuid,boolean,boolean,boolean)', 'EXECUTE'), 'signed-in sharing RPC granted');
select ok(not has_function_privilege('authenticated', 'public.handle_new_user()', 'EXECUTE'), 'auth trigger is not a public RPC');
select * from finish();
rollback;
