FROM node:22-alpine
WORKDIR /app
COPY package.json package-lock.json* ./
COPY apps ./apps
COPY packages ./packages
COPY tsconfig.base.json turbo.json ./
RUN npm ci
COPY . .
CMD ["npm", "run", "dev:marketplace"]
